default: &default
  jwt_secret: <%= ENV['JWT_SECRET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  s3_key: <%= ENV['S3_KEY'] %>
  s3_secret_key: <%= ENV['S3_SECRET_KEY'] %>

development:
  <<: *default
  db_user: <%= ENV['PG_DB_USER'] %>
  db_password: <%= ENV['PG_DB_PASSWORD'] %>

test:
  <<: *default
  db_user: <%= ENV['PG_DB_USER'] %>
  db_password: <%= ENV['PG_DB_PASSWORD'] %>

production:
  <<: *default
